---
- name: update Docker Containers
  community.general.docker_container:
    name: watchtower
    image: containrrr/watchtower
    volumes: /var/run/docker.sock:/var/run/docker.sock
    detach: false
    cleanup: true
    container_default_behavior: no_defaults
    env:
      WATCHTOWER_RUN_ONCE: "true"
      WATCHTOWER_CLEANUP: "true"

- name: Prune unused images containers and volumes
  community.docker.docker_prune:
    containers: true
    images: true
    volumes: true
    builder_cache: true
